#!/bin/bash

# GitHub repository setup script for BiohackMe
# Generated by Ultimate Prompt Maker

# Variables
REPO_NAME="biohackme-react-firebase"
DESCRIPTION="BiohackMe wellness coaching platform built with Next.js and Firebase - SEO-optimized recreation of biohackme.com.au"
WORKSPACE_DIR="/Users/camilla/biohackme-ai-business-team 3"
GITHUB_USER="aigeezer"

echo "🚀 Setting up GitHub repository..."

# Check if gh CLI is installed
if ! command -v gh &> /dev/null; then
    echo "❌ GitHub CLI not found. Installing..."
    brew install gh
fi

# Authenticate if needed
echo "🔐 Checking GitHub authentication..."
gh auth status || gh auth login

# Create repository on GitHub
echo "📦 Creating repository on GitHub..."
gh repo create $REPO_NAME --private --description "$DESCRIPTION"

# Initialize local repository if needed
cd "$WORKSPACE_DIR"

if [ ! -d ".git" ]; then
    echo "📚 Initializing local repository..."
    git init
fi

# Create comprehensive .gitignore
echo "📝 Updating .gitignore..."
cat > .gitignore << 'EOL'
# Dependencies
node_modules/
.pnp
.pnp.js
.yarn/install-state.gz

# Testing
coverage/
*.lcov
.nyc_output

# Next.js
.next/
out/
build/
dist/

# Production
*.production

# Misc
.DS_Store
*.pem
Thumbs.db

# Debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*
.pnpm-debug.log*
lerna-debug.log*

# Local env files
.env*.local
.env.development.local
.env.test.local
.env.production.local

# Vercel
.vercel

# TypeScript
*.tsbuildinfo
next-env.d.ts

# Temporary files
temp/
*.tmp
*.log
*.swp
*.swo
*~

# Firebase
.firebase/
.firebaserc
firebase-debug.log
firestore-debug.log
ui-debug.log
pubsub-debug.log
database-debug.log
firestore.rules
firestore.indexes.json

# IDE
.vscode/
.idea/
*.sublime-project
*.sublime-workspace

# OS files
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db

# Scraped content (contains sensitive data)
scraper/scraped-content.json
scraped-data/

# Build artifacts
*.pid
*.seed
*.pid.lock

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional stylelint cache
.stylelintcache

# Yarn
yarn-error.log
.pnp.*
.yarn/*
!.yarn/patches
!.yarn/plugins
!.yarn/releases
!.yarn/sdks
!.yarn/versions

# SWC
.swc
EOL

# Add all files
echo "📂 Staging files..."
git add .

# Create initial commit
echo "💾 Creating initial commit..."
git commit -m "Initial commit: BiohackMe React + Firebase implementation

- Next.js 14+ with App Router for SEO optimization
- Firebase integration (Firestore, Auth, Functions, Hosting)
- Content scraping setup with Puppeteer
- Mobile-first Tailwind CSS configuration
- AI Business Team agent integration points
- Comprehensive project documentation
- Standard development scripts

Generated by Ultimate Prompt Maker"

# Configure remote
echo "🔗 Configuring remote..."
git remote add origin https://github.com/$GITHUB_USER/$REPO_NAME.git 2>/dev/null || git remote set-url origin https://github.com/$GITHUB_USER/$REPO_NAME.git

# Create and switch to main branch
git branch -M main

# Push to GitHub
echo "📤 Pushing to GitHub..."
git push -u origin main

echo "✅ Repository setup complete!"
echo ""
echo "📍 GitHub URL: https://github.com/$GITHUB_USER/$REPO_NAME"
echo "🔗 Clone URL: git@github.com:$GITHUB_USER/$REPO_NAME.git"
echo ""
echo "Next steps:"
echo "1. Visit https://github.com/$GITHUB_USER/$REPO_NAME/settings"
echo "2. Add collaborators if needed"
echo "3. Configure GitHub Actions for CI/CD"
echo "4. Set up branch protection rules"
echo "5. Add Firebase deployment secrets"
echo ""
echo "To push future changes:"
echo "  git add ."
echo "  git commit -m 'Your commit message'"
echo "  git push"